spack:
  specs:
  - cli11
  - "covfie@0.14:"
  - cmake
  - "g4vg@1.0.3:"
  - "geant4@11.0 cxxstd=20"
  - git
  - "googletest@1.10:"
  - hepmc3
  - mpi
  - ninja
  - nlohmann-json
  - "python@3.6:"
  - "root@6.28: cxxstd=20"
  - "vecgeom@1.2.10: +gdml cxxstd=20"
  concretizer:
    unify: true
  packages:
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.6.3
        prefix: /usr/local/cuda
    root:
      variants: ~davix ~examples ~x ~opengl ~tbb ~rootfit ~python ~math ~gsl cxxstd=20
    all:
      target:
      - x86_64_v3
      variants: +cuda cuda_arch=70 cxxstd=20
      providers:
        blas:
        - openblas
        lapack:
        - openblas
        mpi:
        - openmpi
  config:
    install_tree: /opt/software
  view: /opt/view
