spack:
  specs:
    - cli11
    - "covfie@0.13:"
    - "g4vg@1.0.3:"
    - "geant4@11"
    - "googletest@1.10:"
    - hepmc3
    - nlohmann-json
    - "vecgeom@1.2.10:1 +gdml"
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler: [clang]
      variants: cxxstd=17
