spack:
  specs:
    - "g4vg@1.0.2:"
    - "geant4@11"
    - "googletest@1.10:"
    - hepmc3
    - nlohmann-json
    - "vecgeom@1.2.10: +gdml"
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler: [clang]
      variants: cxxstd=17
