#-------------------------------- -*- yaml -*- ---------------------------------#
# Copyright Celeritas contributors: see top-level COPYRIGHT file for details
# SPDX-License-Identifier: (Apache-2.0 OR MIT)
#-----------------------------------------------------------------------------#
# Run tests on push to develop/backport branches.
#-----------------------------------------------------------------------------#

name: push

on:
  push:
    branches:
      - develop
      - backports/**

concurrency:
  group: push-${{github.ref}}-${{github.run_number}}-${{github.workflow}}
  cancel-in-progress: true

jobs:
  build-ultralite:
    uses: ./.github/workflows/build-ultralite.yml
  build-fast:
    uses: ./.github/workflows/build-fast.yml
  build-docker:
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
  build-spack:
    uses: ./.github/workflows/build-spack.yml
    secrets: inherit
  all:
    needs: [build-fast, build-docker, build-spack]
    runs-on: ubuntu-24.04
    steps:
    - name: Success
      run: "true"

# vim: set nowrap tw=100:
